spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GH_BASIC_CLIENT_ID}
            client-secret: ${GH_BASIC_SECRET_ID}
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/github
            client-authentication-method: client_secret_basic
            scope:  read:user, user:email
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_SECRET_ID}
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            scope:  profile_nickname, account:name, account:email, account:birthday, account:gender
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
